ALTER TABLE TURMA_ALUNO_FREQUENCIA DROP FOREIGN KEY `turma_aluno_frequencia_ibfk_1`;
ALTER TABLE TURMA_ALUNO_FREQUENCIA DROP INDEX matricula_aluno;

ALTER TABLE TURMA_ALUNO_FREQUENCIA DROP COLUMN matricula_aluno;

ALTER TABLE TURMA_ALUNO_FREQUENCIA ADD COLUMN id_aluno BIGINT NOT NULL, ADD CONSTRAINT fk_id_aluno_turma_frequencia FOREIGN KEY (id_aluno) REFERENCES ALUNO (id_aluno);