ALTER TABLE ALUNO_CURSO ADD COLUMN id_aluno BIGINT;

ALTER TABLE ALUNO_CURSO ADD CONSTRAINT fk_aluno_id
    FOREIGN KEY (id_aluno) REFERENCES ALUNO(id_aluno);

ALTER TABLE ALUNO_CURSO DROP FOREIGN KEY ALUNO_CURSO_ibfk_1;
ALTER TABLE ALUNO_CURSO DROP COLUMN matricula_aluno;
