ALTER TABLE FUNCIONARIO DROP FOREIGN KEY `funcionario_ibfk_2`;

ALTER TABLE FUNCIONARIO MODIFY COLUMN id_tipo_funcionario VARCHAR(50) NOT NULL;

ALTER TABLE FUNCIONARIO CHANGE COLUMN id_tipo_funcionario tipo_funcionario VARCHAR(50) NOT NULL;